version: '3'

services:
  db:
    container_name: ${PROJECT_NAME}_db
    build:
      context: ./database
      args:
        - DB_CONTAINER_USER=${DB_CONTAINER_USER}
        - DB_CONTAINER_GROUP=${DB_CONTAINER_GROUP}
    command:
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./logs/db:${DB_LOG_DIR}
      - ./data:${DB_DATA_DIR}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      server_net:
        ipv4_address: ${DB_IP}
    environment:
      - MYSQL_CONTAINER_USER=${DB_CONTAINER_USER}
      - MYSQL_CONTAINER_GROUP=${DB_CONTAINER_GROUP}
      - MYSQL_ROOT_USER=${DB_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DB_NAME=${DB_NAME}

  server:
    container_name: ${PROJECT_NAME}_server
    build:
      context: ./server
      args:
        - SERVER_BUILDDIR=${SERVER_BUILDDIR}
        - SERVER_WORKDIR=${SERVER_WORKDIR}
    restart: always
    ports:
      - ${SERVER_PORT}:80
    networks:
      server_net:
        ipv4_address: ${SERVER_IP}
    environment:
      - SERVER_BUILDDIR=${SERVER_BUILDDIR}
      - SERVER_WORKDIR=${SERVER_WORKDIR}
      - DB_HOST=${DB_IP}
      - DB_USER=${DB_ROOT_USER}
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}

networks:
  server_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
